### ISSUE TITLE
请问：如何在回调函数里传参？

### ISSUE THREAD

**Issue by zhanghuid** [mm-sam/vue-plupload#2]
### html页面
``` vue
<vue-plupload @added="handleAdded" @progress="handleProgress" @error="handleError" @uploaded="handleUploaded(xxxx)" :options.sync="uploadOpt"></vue-plupload>
```
### js
```js
new vue({
   methods: {
      handleUploaded: function(xxx) {
          // code
      }
   }
});
```
问题：
这里的xxx确实是有传参了,且有值。但是[self.$emit("uploaded", up, file, result)第113行](https://github.com/MMHK/vue-plupload/blob/5b36228e55bc93e702cb65b168e1f93e73d65402/src/vue-plupload.vue)里的三个回调参数丢失了。

**Comment by mm-sam** [comment]
https://github.com/MMHK/vue-plupload/blob/master/docs/index.html
请看sample

**Comment by zhanghuid** [comment]
可能是我表达有问题。
场景：我不是要传参数给后台。而是，简单地**传给回调函数**，这样，方便回调后（file 上传成功后调用的回调函数），可以拿到我当时传的值。最后**根据后台回传的数据动态的改变传的值**。

**Comment by zhanghuid** [comment]
### 场景：
因为，我是在for 循环中，需要把item的对象传给上传文件结束后的回调函数。需要动态改变item对象的某一个属性的值
### 解决方案：
方案1 是可以直接传给后端，等response 的时候再返回
方案2， 直接污染 file 对象
### 我采取方案1：
把当前item的标塞进去，传给后台，之后，上传成功后，回调时，回传回来下标，最后可以根据下标得到对象。再改具体的属性
